---
services:
  nautobot:
    environment:
      - "NAUTOBOT_DB_ENGINE=django.db.backends.postgresql"
  db:
    image: "postgres:13-alpine"
    
    command:
      - "-c"
      - "max_connections=200"
    env_file:
      - "development.env"
      - "creds.env"
    volumes:
      - "postgres_data:/var/lib/postgresql/data"
      # - "./initdb:/docker-entrypoint-initdb.d"
      - guac_init:/docker-entrypoint-initdb.d
      - ./01-initdb.sh:/docker-entrypoint-initdb.d/01-initdb.sh
    depends_on:
      - guacamole-preparation
    healthcheck:
      test: "pg_isready --username=$$POSTGRES_USER --dbname=$$POSTGRES_DB"
      interval: "10s"
      timeout: "5s"
      retries: 10

volumes:
  postgres_data: {}
